<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="card-header">
      <a href="<?= base_url('');?>" class="btn btn-info float-right btn-sm"><i class="fas fa-backward"></i> Kembali</a>          
    </div>
    <?php $this->view('message'); ?>
    <div class="row">
      <div class="col-md-12">
        <!-- Profile Image -->
        <div class="card card-info card-outline">
          <div class="card-body box-profile">
            
            <p align="center" style="margin-bottom:.0001pt;text-align:center;line-height:150%;"><strong><span style="line-height:150%; font-size:14.0pt; ">NILAI PERJUANGAN DAN NILAI KARAKTER  JENDERAL SUDIRMAN </span></strong></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:21.3pt;line-height:150%;"><span style="line-height:150%; font-size:12.0pt; ">Saat melakukan gerilyanya banyak sekali peran yang dilakukan  oleh Jenderal Sudirman. Selain peran yang ditunjukkan oleh Jenderal Sudirman,  terdapat perilaku yang dapat dijadikan tauladan. Berikut nilai perjuangan dan  nilai karakter yang ditunjukkan Jenderal Sudirman saat bergerilya. </span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="line-height:150%; font-size:12.0pt; color:black; ">Nilai Perjuangan</span></strong><span style="font-size:12.0pt; "> </span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Nilai perjuangan yang ditunjukkan Panglima Besar Jenderal Sudirman  sangatlah jelas terlihat. Sebelum menuju trenggalek, rombongan dan Pak Dirman  dikepung oleh pasukan Belanda saat di Ponorogo. Hujan lebat dan ditambah  pasokan pangan yang kurang membuat para rombongan gerilya tidak sempat memakan  nasi selama kurang dari 3 hari. Saat masuk di Trenggalek tepatnya di Desa  Dongko, Pak Dirman dalam keadaan sakit. Fisiknya melemah seakan tidak kuat  untuk meneruskan gerilyanya. Namun dengan tekad dan semangat yang kuat beliau  tetap berjuang dan memimpin pasukkan untuk melanjutkan gerilyanya. Hal tersebut  merupakan nilai perjuangan yang dapat dijadikan sebagai suri tauladan seorang  pahlawan dalam mempertahankan kemerdekaan Indonesia. Tidak sekedar itu,  perjuangan Panglima Besar Jenderal Sudirman sudah ditunjukkan ketika beliau  memutuskan atas izin Ir. Soekarno untuk melakukan perang gerilya menghadapi  serangan agresi militer Belanda ke-II. Perjuangan yang hebat dilakukan rombongan  gerilya Jenderal Sudirman mulai dari Yogyakarta sampai dengan wilayah </span><span style="font-size:12.0pt; ">Trenggalek<span style="color:black; ">.</span></span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Panjang rute seluruh Rute Gerilya </span><span style="font-size:12.0pt; ">Panglima<span style="color:black; "> Besar Jenderal Sudirman melalui 75 buah kota besar dan kecil yang secara  teoritis meliputi 900 kilometer, namun pada kenyataannya mencapai panjang 1.009  kilometer yang sebagian besar </span>ditempuh<span style="color:black; "> dengan  berjalan kaki. Suatu pengorbanan luar biasa yang ditunjukkan prajurit dan  Jenderal Sudirman (Puar, 1981:152). <strong></strong></span></span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="font-size:12.0pt; color:black; ">Nilai Religius</span></strong></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Banyak artikel dan buku yang membahas bahwa sosok Sang Jenderal  Sudirman memiliki sifat yang religius. Pernyataan tersebut dapat ditemukan saat  Jenderal Sudirman melewati Trenggalek. Dijelaskan dalam (Atmojo, 1985:99) saat  rombongan ditahan di Batalyon 102 dan Kapten Supardjo sedang menghadap Mayor  Zainal Fanani, maka Pak Dirman yang ditemani Cokroaminoto meminta untuk  diizinkan menuju masjid terdekat karena waktu sudah menunjukkan sholat Magrib.  Tidak hanya itu, dalam Buku Sepekan Bersama Sang Jenderal (Murtono, 2008:40)  dijelaskan bahwa saat sang Jenderal Sudirman di Desa Bodag dalam keadaan kurang  sehat beliau tetap melaksanakan sholat dengan tepat waktu. Hal tersebut  dibuktikan dengan adanya peninggalan Al-Quran dan Sajadah yang dipakai Sang  Jenderal Sudirman. Panglima Jenderal Sudirman merupakan sosok yang sangat  religius dan gemar beribadah.</span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="font-size:12.0pt; color:black; ">Nilai Kepemimpinan</span></strong></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Dari seorang tokoh yang sangat melegenda Panglima Jenderal  Sudirman dapat dijadikan suri tauladan dalam hal kepemimpinan, beliau </span><span style="font-size:12.0pt; ">merupakan<span style="color:black; "> sosok pemimpin yang bijaksana dan cekatan dalam melakukan dan menanggapi suatu  permasalahan. Hal tersebut dibuktikan saat gerilya melewati Trenggalek tepatnya  di Bendorejo, bahwa Mayor Batalyon 102 Zainal Fanani mengetahui bahwa <strong>&ldquo;seseorang tawanan&rdquo;</strong> tersebut adalah  pimpinan besar mereka. Maka secara tegas dan cekatan, Jenderal Sudirman  mengambil langkah cepat untuk memerintahkan Zainal Fanani menghubungi Kolonel  Soengkono di Kediri. Seorang pemimpin juga memiliki jiwa tanggung jawab yang  besar hal tersebut juga ditunjukkan saat </span>Soekarno<span style="color:black; "> menyuruh Sudirman untuk tetap tinggal bersamanya tetapi Sudirman  menolaknya dan tetap berjuang </span>di tengah<span style="color:black; "> anak  buah untu</span>k<span style="color:black; "> meneruskan perjuangan (Dinas  Pembinaan Mental Angkatan Darat, 2008:48). </span></span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Hal tersebut dipertegas dalam catatan perjalanan yang ditulis oleh  Soegeng Rahardjo (Badan Arsip Provinsi Jawa Timur, 1996) yang berjudul  &ldquo;Mengawal Perjalanan Pangsar Jenderal Soedirman Ke Jawa Timur Untuk Memimpin  Perang Gerilya Tahun 1948-1949. Dalam catatan tersebut memuat peristiwa gerilya  yang dilakukan Jenderal Sudirman dan rombongan mulai dari wilayah Jogja sampai  di daerah Jawa Timur tepatnya di wilayah Trenggalek. Catatan ini menjelaskan  perjalanan rombongan dan </span><span style="font-size:12.0pt; ">koordinasi<span style="color:black; "> setiap wilayah ketika  rombongan menuju ke tempat berikutnya. Jenderal Sudirman selalu berkomunikasi  dengan batalyon-batalyon yang dilalui rute gerilya untuk memastikan keadaan  aman dan jauh dari pantauan Belanda. Hal tersebut membuktikan perjuangan  Jenderal Sudirman untuk </span>mempertahankan<span style="color:black; "> Kemerdekaan Indonesia dari tangan Belanda. </span></span></p>
            <p align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;text-indent:14.7pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-3-1.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="244" height="340" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-3-1.jpg"></a></span><span style="font-size:12.0pt; color:black; ">  </span><span style="font-size:12.0pt; color:black; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-3-2.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img width="282" height="336" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-3-2.jpg"></a></span><span style="font-size:12.0pt; color:black; "> </span></p>
            <p align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;text-indent:14.7pt;line-height:normal;border:none;"><strong><span style="font-size:10.0pt; color:black; ">Gambar 1. </span></strong><span style="font-size:10.0pt; color:black; "> Foto  Catatan Perjalanan Soegeng Rahardjo</span></p>
            <p align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;text-indent:14.7pt;line-height:normal;border:none;"><a name="_heading=h.gjdgxs"></a><span style="font-size:10.0pt; color:black; ">(<strong>Sumber:</strong> Badan Arsip Provinsi Jawa Timur, 1996)</span></p>
            <p align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;text-indent:14.7pt;line-height:normal;border:none;"><span style="font-size:10.0pt; color:black; ">&nbsp;</span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="font-size:12.0pt; color:black; ">Nilai Kepahlawanan</span></strong></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:14.7pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Panglima Besar Jenderal Sudirman merupakan sosok yang berani dan  tidak takut menghadapi bahaya. Saat melakukan gerilya, rombongan dan Pak Dirman  benar-benar pahlawan. Hal tersebut karena seorang pahlawan rela berkorban untuk  mementingkan kepentingan Negara dibanding kepentingan pribadi, ikhlas dalam  melakukan perbuatannya dan cinta tanah air. Hal tersebut ditunjukkan oleh Pak  Dirman, beliau benar-benar mengutamakan keselamatan Negara dibandingkan  keselamatan kesehatannya. Karakter kepahlawanan melekat pada diri Jenderal  Sudirman yang selalu semangat dan ikhlas dalam berkorban, tidak pantang  menyerah dan memiliki keberanian dalam membela Kemerdekaan Indonesia. </span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;border:none;"><strong><span style="font-size:12.0pt; color:black; ">Nilai Nasionalisme</span></strong></p>
            <p style="margin-bottom:.0001pt;text-align:justify;text-indent:14.7pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Sebagai tokoh yang memiliki tanggung jawab besar pada saat ini  menunjukkan bahwa Panglima Besar Jenderal Sudirman memiliki nasionalisme yang  tinggi terhadap Negara Indonesia, agar Indonesia tetap merdeka dan terbebas  dari serangan Belanda. Beliau lebih mementingkan kepentingan dan keselamatan  bangsa daripada kepentingan suatu golongan. Tidak hanya itu beliau juga tetap  menjunjung tinggi suatu keberagaman tanpa membedakan suku, ras, agama, golongan  dalam mempertahankan kemerdekaan Indonesia. </span></p>
            <p style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><span style="font-size:12.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal">&nbsp;</p>

          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->        
      </div>      
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
