<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="card-header">
      <a href="<?= base_url('');?>" class="btn btn-info float-right btn-sm"><i class="fas fa-backward"></i> Kembali</a>          
    </div>
    <?php $this->view('message'); ?>
    <div class="row">
      <div class="col-md-12">
        <!-- Profile Image -->
        <div class="card card-info card-outline">
          <div class="card-body box-profile">
            
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:150%;"><strong><span style="line-height:150%; font-size:14.0pt; ">PERAN DAN JEJAK JENDERAL SUDIRMAN DI  TRENGGALEK</span></strong></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-size:14.0pt; ">&nbsp;</span></strong></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="line-height:150%; font-size:12.0pt; ">Rute pertama yaitu rute awal  keberangkatan gerilya menuju arah Ponorogo melewati Trenggalek dan menuju  Kediri</span></strong><span style="font-size:12.0pt; ">. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Atmojo (1985:98) menjelaskan bahwa tanggal 23 Desember 1948  seluruh rombongan dari Wonogiri menuju Ponorogo dan dilanjutkan menuju wilayah  Trenggalek. Di Ponorogo rombongan tidak istirahat lama dan melanjutkan  perjalanan sekitar pukul 4 sore menuju Desa Bendorejo sebelah tenggara  Tulungagung, wilayah tersebut sekarang masuk ke dalam administratif wilayah  Trenggalek bagian Kecamatan Pogalan. Saat menuju Pogalan para rombongan sangat  berhati-hati karena di bagian utara Trenggalek tepatnya Kecamatan Bendungan terdapat  pabrik kopi milik Belanda yang bernama Ndilem Wilis. Cerita dari masyarakat  bahwa pabrik tersebut milik bangsawan Belanda yang bernama Mr. Van Dilem. Hal  tersebut membuat para rombongan harus berhati-hati saat gerilya karena bisa  saja menjadikan situasi yang berbahaya (Soyomukti, N &amp; Subekti, 2016). Pada  saat di Trenggalek rombongan berhenti sebentar dan ditahan oleh Batalyon 102  bagian Trenggalek karena rombongan dicurigai. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Saat itu wilayah Trenggalek merupakan tanggung jawab  Batalyon 102 yang dipimpin oleh Mayor Zainal Fanani. Rombongan gerilya yang  dicurigai lalu ditahan oleh penjaga namun rombongan tidak dilucuti. Situasi dan  kondisi saat itu sedang tegang sehingga menyebabkan penjagaan sepanjang jalan  setiap daerah memang diperketat dan suasana curiga memang berkecamuk termasuk  juga di wilayah Batalyon 102. Dalam buku Rute Gerilya Panglima Besar Jenderal  Sudirman (Dinas Pembinaan Mental Angkatan Darat, 2008:100) menjelaskan bahwa  rombongan Pak Dirman saat itu bersama dengan Kapten Supardjo dan Pak Harsono  Cokroaminoto. Kapten Pardjo yang digeledah oleh penjaga hanya mengatakan bahwa  rombongan membawa <strong>&ldquo;seorang tawanan&rdquo;. </strong></span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Di situasi lain karena waktu sudah magrib dan Kapten  Supardjo belum balik ke rombongan maka Pak Dirman yang didampingi dengan Pak  Harsono Cokroaminoto yang sewaktu itu dalam rombongan bertindak sebagai <em>&ldquo;penasehat politik&rdquo;</em> meminta waktu dari  penjaga untuk melakukan sholat Magrib di masjid yang dekat dengan tempat  tersebut lalu tidak lama kemudian datanglah Komandan Batalyon 102 yaitu Zainal  Fanani. Atmojo (1985:99) menjelaskan bahwa Komanan Zainal Fanani datang menemui  Pak Harsono Cokroaminoto dan menanyakan tawanan yang ada di masjid tersebut.  Berhubung Pak Harsono Cokroaminoto hanya mengatakan seorang tawanan maka Zainal  Fanani langsung menghampiri tawanan tersebut. Alangkah terperanjat dan memberi  hormat secara militer Mayor Zainal Fanani ketika mengetahui tawanan yang  dimaksud Pak Harsono Cokroaminoto tersebut adalah Panglima Besar Jenderal  Sudirman. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Setelah mengetahuinya, para pasukan membawa Pak Dirman  bersama rombongan ditempatkan yang lebih baik dengan penjagaan yang ketat. Pak  Dirman lalu ditempatkan di rumah K. Abdul Mukti yang merupakan imam di masjid  tempat rombongan melakukan sholat. Di sini Pak Dirman dan K. Abdul Mukti saling  bertukar pikiran, nasehat-menasehati dan tukar menukar tongkat (Bahasa Jawa: <em>teken</em>) sebagai kenangan. </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; "><p align="center" style="text-align:center;"><a name="_heading=h.gjdgxs"></a><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-1.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img  class="img-fluid" width="241" height="332" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-1.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 1</span></strong><span style="font-size:10.0pt; ">. Foto Kyai Abdul Mukti</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">(Dokumentasi Peneliti, 2020) </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Berdasarkan wawancara Ibu Anik (selaku anak Kyai Abdul  Mukti) dan Bapak Yasin (selaku keponakan Kyai Abdul Mukti) tanggal 8 Desember  2020 menjelaskan bahwa rombongan datang sekitar pukul 4 sore. Saat itu tempat  ini masih sepi, penjagaan para rombongan dilakukan dengan ketat. Ibu Anik juga  menjelaskan bahwa rumah yang disinggahi rombongan di tempat ini masih mirip  pondasinya dan belum berubah, hanya saja ada renovasi perbaikan rumah. Ibu Anik  mendapatkan informasi tersebut sudah sejak kecil secara turun temurun.</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; "><p align="center" style="text-align:center;"><a name="_heading=h.gjdgxs"></a><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-2.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="379" height="252" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-2.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 2</span></strong><span style="font-size:10.0pt; ">. Foto Rumah Singgah tampak samping</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">(Dokumentasi Peneliti, 2020) </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Bu Anik juga menjelaskan bahwa Kyai Abdul Mukti menceritakan  tentang peristiwa penting tersebut dalam lembaran-lembaran kertas dan bisa  dijadikan bukti, hanya saja catatan penting dari Kyai Abdul Mukti dibawa oleh  anaknya yang lain di luar kota. Tidak hanya itu, Pak Yasin juga menyampaikan  saat itu dirinya masih kecil saat Pak Dirman datang. Pak Yasin memberikan  informasi bahwa masjid yang disinggahi rombongan sudah direnovasi, hanya bagian  tengah masjid yang pondasinya masih mirip. Barang-barang sebagai tanda bahwa  Pak Dirman dan rombongan tersebut juga sudah dibawa oleh para TNI untuk dibawa  dan dimuseumkan. Peninggalan tersebut berupa tongkat atau dalam bahasa jawanya <em>&ldquo;teken&rdquo;.</em></span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-3.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="300px" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-3.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 3</span></strong><span style="font-size:10.0pt; ">. Foto Bagian Tengah Masjid yang Disinggahi Rombongan</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">(Dokumentasi Peneliti, 2020) </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Pak Sudirman sempat beristirahat sejenak karena kondisi  fisik beliau yang menurun (Wilis Abdul, 2016:101). Di sisi lain para rombongan  berkoordinasi untuk melakukan rute perjalanan menuju posko yang baru karena ada  informasi bahwa Belanda mengetahui posisi Pak Sudirman dan rombongan. Segeralah  Zainal Fanani selaku Komandan yang bertanggung jawab di wilayah Trenggalek  diberikan perintah secara langsung oleh Pak Dirman. </span></p>
            <p class="MsoNormal" style="margin-top:0cm;margin-right:59.15pt;margin-bottom:.0001pt;margin-left:49.65pt;text-align:justify;text-indent:1.0cm;line-height:normal;"><em><span style="font-size:10.0pt; ">&ldquo;………Mayor Zainal Fanani  diperintahkan Pak Dirman untuk segera menghubungi Kolonel Soengkono lewat  telephone, melaporkan kedatangan Pak Dirman dan meminta saran kepada Pak  Soengkono mengenai rute perjalanan Pak Dirman yang aman menuju Posko Baru. Rute  tersebut sudah direncanakan dan disiapkan oleh Pak Soengkono. Mayor Zainal  Fanani mendapatkan jawaban dari Pak Soengkono dan akan segera mengirimkan mobil  untuk menjemput rombongan untuk menuju Kediri&rdquo;</span></em></p>
            <p class="MsoNormal" style="margin-top:0cm;margin-right:45.0pt;margin-bottom:.0001pt;margin-left:42.55pt;text-align:justify;text-indent:1.0cm;line-height:normal;"><em><span style="font-size:10.0pt; ">&nbsp;</span></em></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:45.0pt;margin-bottom:.0001pt;margin-left:42.55pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">Dinas  Pembinaan Mental Angkatan Darat (2008:101)</span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:45.0pt;margin-bottom:.0001pt;margin-left:42.55pt;text-align:center;text-indent:1.0cm;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Kutipan tersebut menjelaskan bahwa Mayor Zainal Fanani  diperintahkan langsung oleh Panglima Besar Jenderal Sudirman untuk menghubungi  Kolonel Soengkono lewat telepon untuk dimintai saran dan pendapat. Sebagaimana  yang telah direncanakan dan disiapkan oleh Kolonel Soengkono maka beberapa jam  kemudian mobil penjemputan datang, rombongan Pak Dirman melanjutkan gerilya  menuju ke Kediri melewati wilayah Tulungagung bersama dengan Perwira Staf  Kolonel Soengkono (Atmojo S, 1985:99). </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Sehari setelah kedatangan Pak Dirman dan rombongan di rumah  K. Abdul Mukti tepatnya tanggal 24 Desember 1948, rumah beliau dijaga ketat  oleh tentara dan terjadi kejadian yang luar biasa. Di saat siang hari ketika  Abdul Mukti masih di masjid tiba-tiba terdapat pesawat terbang Belanda yang  meraung-raung terbang sangat rendah mengitari masjid dan rumahnya. Tiba-tiba  pesawat terbang menjatuhkan sebuah bom yang dijatuhkan di serambi masjid  sebelah selatan. Seluruh tanah di rumah dan sekitar masjid bergetar (Willis  Abdul, 2016:101). Bom tersebut merupakan tanda bahwa Belanda telah mengetahui  bahwa Pak Sudirman ada di tempat ini, namun untung saja para rombongan telah  meninggalkan Trenggalek menuju ke posko yang baru. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Rute tersebut merupakan rute pertama yang dilewati rombongan  dalam gerilya melalui wilayah Trenggalek. Mayor Zainal Fanani selaku Komandan  Batalyon 102 yang bertanggung jawab atas wilayah Trenggalek dan memperlakukan  rombongan dengan baik serta penjagaan yang ketat sampai rombongan dijemput  mobil menuju arah Kediri dan di Kediri rombongan disambut langsung oleh Kolonel  Soengkono. Saat rute perjalanan pertama di Trenggalek, wilayah ini hanya  dilalui satu titik tepatnya di Desa Bendorejo, Kecamatan Pogalan-Trenggalek. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:150%;"><strong><span style="font-size:12.0pt; ">Rute kedua yaitu rute gerilya balik  dari arah Madiun melewati Ponorogo- Trenggalek dan dilanjutkan menuju Pacitan</span></strong></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Pasca rute awal dari Trenggalek, para rombongan menuju  Kediri yang telah dikawal oleh Kapten Supardjo. Di Kediri para rombongan  gerilya melakukan perjalanan selama 3-4 hari terhitung mulai tanggal 24-26  Desember 1948 dan dilanjutkan menuju daerah Nganjuk. Di wilayah ini Pak Dirman  melakukan istirahat di Desa Bajulan karena ada beberapa wilayah yang  mendapatkan perlawanan dari Belanda. Setelah merasa aman, para rombongan  gerilya melanjutkan perjalanannya menuju Desa Jambu di wilayah Madiun dan  sampai pada tanggal 9 Januari 1949 karena memerlukan waktu yang agak lama. Di  Madiun para rombongan melakukan gerilya selama 9 hari dan dilanjutkan menuju  Desa Sedayu, Ponorogo (Dinas Pembinaan Mental Angkatan Darat, 2008:108-115). </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:1.0cm;line-height:150%;"><span style="font-size:12.0pt; ">Sesampainya di Desa Sedayu tanggal 18 Januari 1949 sekitar  pukul 14.00 rombongan gerilya bertemu dengan pasukan Belanda sehingga terjadi  situasi yang menegangkan. Belanda sudah mengetahui jika Pak Dirman berada di  Sedayu sehingga Belanda melakukan pencarian terhadap Pak Dirman tersebut. Perjalanan  di Ponorogo memerlukan waktu selama kurang lebih 10 hari karena rombongan  terhalang oleh pasukan Belanda sehingga membutuhkan persembunyian di  hutan-hutan. Di wilayah ini Belanda yakin bahwa Pak Dirman ada di desa ini dan  terus melakukan penangkapan. Belanda melakukan penggeledahan dan pemeriksaan  rumah-rumah yang ada di wilayah tersebut. Situasi semakin mencekam ketika para  rombongan gerilya masih belum aman dari kepungan Belanda dan justru rombongan  tidak sengaja menuju ke tempat markas Belanda, jaraknya kurang lebih 1.5 km.  Tidak ada peta dan informasi yang akurat yang menyebabkan kekeliruan tersebut.  Tetapi untungnya Belanda tidak mengadakan gerakan pembersihan di daerahnya  sendiri. Setelah mengetahui hal tersebut rakyat setempat menyarankan untuk melanjutkan  perjalanan di wilayah Trenggalek sebelum Belanda mengetahui keberadaan  rombongan yang dekat dengan markas Belanda (Dinas Pembinaan Mental Angkatan  Darat, 2008:118). </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Setelah dari Ponorogo perjalanan dilanjutkan di wilayah  Trenggalek. Sebelum menuju wilayah Trenggalek, rombongan berhenti sejenak di  Desa Tumpak Pelem Ponorogo. Kapten Supardjo lalu mencari hubungan dengan  Komando Distrik Militer di Trenggalek (Atmojo S, 1985:107). </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:150%;"><span style="font-size:12.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-4.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="609" height="301" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-4.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 4.</span></strong><span style="font-size:10.0pt; "> Peta Rute Gerilya Panglima Besar  Jenderal Sudirman di Situs Persinggahan Jenderal Sudirman di Desa Bodag,  Kabupaten Trenggalek</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><span style="font-size:10.0pt; ">(<strong>Sumber:</strong> Dokumentasi Peneliti, 2020)</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Untuk kedua kalinya wilayah Trenggalek dilalui perjalanan  Perang Gerilya. Rute perjalanan kedua ini berbeda dengan sebelumnya, jika rute  sebelumnya yaitu dari Ponorogo-Trenggalek-Kediri yang hanya dilalui satu titik  di Desa Bendorejo maka rute selanjutnya yaitu dari arah Madiun-Ponorogo  melewati Trenggalek dan dilalui sebanyak 4 titik jejak gerilya. Berikut  penjelasannya:</span></p>
            <ol>
              <strong><span style="line-height:150%; font-size:12.0pt; color:black; ">Desa Nglongsor,  Kecamatan Tugu Kabupaten Trenggalek</span></strong>
            </ol>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Setelah melalui beberapa daerah seperti Tulungagung, Kediri,  Nganjuk, Madiun, Ponorogo, rombongan sampai lagi di wilayah Trenggalek tepatnya  pada tanggal 28 Januari 1949. Di Desa ini merupakan jalur yang kedua dalam rute  gerilya melewati Trenggalek. Para rombongan menuju rumah seorang petani bernama  Pak Kaeran. Para petinggi seperti Lurah Karmidi, Carik Maidin, Jogoboyo Ruwek  dan Kamituwo Mariman ikut serta menyambut kedatangan rombongan. Saat  beristirahat disini, Pak Dirman dalam keadaan batuk-batuk karena tenaganya yang  terkuras habis saat di wilayah Sedayu. Di Desa Nglongsor ini rombongan hanya  bermalam satu malam dan dilanjutkan menuju wilayah Suruh Wetan. </span></p>
            <ol>
              <strong><span style="font-size:12.0pt; color:black; ">Desa </span></strong><strong><span style="font-size:12.0pt; ">Suruh Wetan<span style="color:black; ">, Kecamatan Suruh  Kabupaten Trenggalek</span></span></strong>
            </ol>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Setelah melakukan semalam di Desa Nglongsor, Kecamatan Tugu.  Rombongan akhirnya sampai di Desa Suruh Wetan pada tanggal 29 Januari 1949. Di  tempat ini merupakan daerah yang cocok digunakan tempat istirahat Panglima  Sudirman karena kondisi fisiknya yang semakin menurun.  Namun Jenderal Sudirman bersikeras untuk  tetap melanjutkan perjalanan gerilyanya menuju Desa Dongko. Saat kedatangan di  Desa Suruh rombongan datang secara bergelombang untuk meminimalisir terjadinya  keramaian dan menjaga kondisi agar tetap stabil. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Mengutip dari pernyataan Pak Istajab dalam (Murtono, 2008)  dijelaskan bahwa rombongan datang dari Nglongsor menuju rumah Bapak Mukijan  seorang petani di wilayah tersebut dan beristirahat di langgar depan rumah  Bapak Mukijan. Tempat ini dijaga ketat oleh tentara dan sang jenderal saat itu  sedang keadaan kurang fit sehingga mendatangkan dukun urut bernama Nurhadi. </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-5.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="284" height="368" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-5.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:14.2pt;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 5</span></strong><span style="font-size:10.0pt; ">. Foto Bapak Istajab selaku Saksi Hidup</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:14.2pt;line-height:normal;"><span style="font-size:10.0pt; ">(<strong>Sumber</strong>: Murtono,  2008:13) </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:14.2pt;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <ol>
              <strong><span style="font-size:12.0pt; color:black; ">Desa Dongko, Kecamatan  Dongko Kabupaten Trenggalek</span></strong>
            </ol>
            <p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:14.2pt;text-align:justify;text-indent:21.8pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Perjalanan gerilya pun dilanjutkan menuju daerah Dongko. Para  rombongan sampai di Desa Dongko pada tanggal 30 Januari 1949. Saat menuju  Dongko dari Suruh Pak Dirman ditandu oleh 4 orang </span><span style="font-size:12.0pt; ">t<span style="color:black; ">entara  karena memang kondisi fisiknya yang melemah. Rombongan datang di Desa Dongko  menuju rumah Bapak Kartodiharjo. Rombongan tersebut diikuti oleh para  pengawal-pengawalnya untuk menjaga Pak Dirman dalam keadaan aman. Saat berada  di Trenggalek, Komando Distrik Militer (KDM) Trenggalek sangat memperhatikan  segala kebutuhan rombongan. Tidak hanya itu penjagaan sangat ketat dan  kebutuhan pangan juga tercukupi. Rombongan </span>disini<span style="color:black; "> bermalam satu malam dan dilanjutkan menuju arah pantai selatan tepatnya  wilayah Panggul<strong></strong></span></span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:14.2pt;text-align:center;line-height:150%;border:none;"><strong><span style="font-size:12.0pt; color:black; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-6.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="287" height="361" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-6.jpg"></a></span></strong><strong><span style="font-size:12.0pt; color:black; "> </span></strong></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:14.2pt;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 6</span></strong><span style="font-size:10.0pt; ">. Foto Persinggahan Jenderal Sudirman di Desa Dongko</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:14.2pt;line-height:normal;"><span style="font-size:10.0pt; ">(<strong>Sumber: </strong>Murtono,  2008:16) </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <ol>
              <strong><span style="font-size:12.0pt; color:black; ">Desa Bodag, Kecamatan  Panggul Kabupaten Trenggalek</span></strong>
            </ol>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Pada tanggal 31 Januari 1949, para rombongan melanjutkan  perjalanannya ke wilayah Panggul bagian utara yaitu tepatnya desa Bodag. Di  Desa Bodag, para rombongan menginap selama 3 malam 4 hari sampai dengan tanggal  3 Februari 1949. Rombongan menginap di rumah Janda Bapak Ngabdi yaitu Ibu  Jamilatun. Di Desa Bodag, rombongan terbagi menjadi 2 kelompok. Kelompok  pertama terdiri dari Jenderal Sudirman atau yang dikenal dengan Pak Dirman,  lalu dokter pribadi Pak Dirman, dan beberapa pengawal Pak Dirman yang menginap  di Rumah Ibu Jamilatun. Kelompok kedua para pejabat dan pengawal lain menginap  di rumah Bapak Partodiwiryo yang saat itu menjabat sebagai Carik. Pada saat di  Desa Bodag, para rombongan disambut dengan hangat oleh petinggi desa.  Partowidiryo sebagai Carik Desa Bodag Tahun 1949 sangat memperhatikan dan  bertanggung jawab atas kedatangan rombongan gerilya Panglima Besar Jenderal  Sudirman dengan bantuan para Bebahu Desa (pelayan) Desa Bodag saat itu  (Murtono, 2008). Pemilihan tempat di Desa Bodag didasarkan atas tempat wilayah  yang sangat strategis karena dikelilingi oleh perbukitan dan jauh dari pusat  wilayah. Pada saat itu keramaian terdapat di wilayah Panggul sedangkan Desa  Bodag berada di bagian utara dari Kecamatan Panggul. Di tempat ini para  rombongan menginap selama 3 malam 4 hari 1949 (Atmojo, 1985:106). Sesampainya  di rumah Janda Ibu Jamilatun, beliau mulai menyiapkan segala kebutuhan yang  dibutuhkan rombongan dan Pak Dirman, yang dibantu oleh warga Desa Bodag yang  telah ditunjuk Pak Partodiwiryo. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Murtono (2008:38) dalam buku karangan berjudul &ldquo;Sepekan  Bersama Sang Jenderal&rdquo; menjelaskan bahwa Ibu Jamilatun juga dibantu oleh warga  Desa Bodag dalam menyambut rombongan gerilya. Warga tersebut antara lain: 1.)  Pak Pono (Pegawai Penerangan) yang bertugas menyiapkan perlengkapan ibadah  seperti Sajadah, Al-Quran dan penerangan cahaya, 2). Ibu Ponirah sebagai juru  masak, 3.) Ibu Tawinem sebagai juru asah-asah, dan 4.) Pak Soiran sebagai juru  panimbo (pencari air). </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-7.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="300" height="298" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-7.jpg"></a></span><span style="font-size:12.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 7.</span></strong><span style="font-size:10.0pt; "> Monumen sebagai Tanda Persinggahan  Jenderal Sudirman di Desa Bodag </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-indent:36.0pt;line-height:normal;"><span style="font-size:10.0pt; ">                                                  (<strong>Sumber:</strong> Dokumentasi Peneliti, 2020)</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Saat ini, Rumah Persinggahan Jenderal Sudirman tidak  ditempati dan hanya ditempati keluarga saat ada kegiatan besar seperti Idul  Fitri atau hari libur Nasional. Akan tetapi, walaupun tidak ditempati rumah ini  tetap terjaga dan terdapat juru kunci di tempat ini. Selain itu, rumah ini  menjadi saksi bahwa di tempat ini terdapat sejarah yang perlu dikenang sehingga  dari Pemerintah Kabupaten Trenggalek melalui Dinas Pariwisata dan Kebudayaan  Trenggalek tempat ini dijadikan sebagai <strong>&ldquo;Situs  Pesanggrahan Jendral Sudirman&rdquo; </strong>yang telah dilindungi oleh Undang-Undang  Nomor 11 Tahun 2010 tentang Cagar Budaya. </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><span style="font-size:10.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-8.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="422" height="331" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-8.jpg"></a></span><span style="font-size:10.0pt; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><strong><span style="font-size:10.0pt; ">Gambar 8.</span></strong><span style="font-size:10.0pt; "> Simbol Situs Pesanggrahan Jenderal  Sudirman oleh Pemerintah Kabupaten Trenggalek melalui Dinas Pariwisata dan  Kebudayaan Trenggalek </span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:150%;"><span style="line-height:150%; font-size:10.0pt; ">(<strong>Sumber:</strong> Dokumentasi Peneliti, 2020)</span></p>
            <p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;text-indent:36.0pt;line-height:normal;"><span style="font-size:10.0pt; ">&nbsp;</span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Jika dilihat dari konstruksi bangunannya, rumah ini masih  mirip seperti saat Jenderal Sudirman singgah tahun 1949. Namun terjadi beberapa  kali renovasi baik yang dilakukan oleh pihak keluarga, pemerintah daerah atau  pihak Tentara Nasional Indonesia (TNI) Angkatan Darat (AD) setempat. Renovasi  yang dilakukan berupa penggantian genting dan tiang rusuk pada rumah. Hal  tersebut juga ditandai dengan adanya simbol bahwa rumah ini telah direnovasi  dan diresmikan pada tanggal 5 November 2003 oleh Letnan Kolonel R. Srenggono  Putro. Bapak Sukemi saat wawancara (2020) selaku cucu Bapak Ngabdi menyampaikan  bahwa ada banyak dampak yang dirasakan ketika bersinggah di sini. Salah satu  hal yang mencolok adalah tempat ini sering dikunjungi baik dari pemerintah  daerah, TNI, pelajar/mahasiswa dan kalangan umum. Beliau juga menyampaikan  bahwa tempat ini juga sudah direnovasi dan renovasi terakhir juga dibangun  monumen sebagai simbol tempat ini menjadi sejarah bangsa Indonesia. Bapak  Sukemi juga menjelaskan terdapat benda-benda yang digunakan Pak Dirman disini  dan masih disimpan sebagai peninggalan bahwa rombongan pernah datang disini.  Sebagai carik di desa tersebut, Pak Partodiwiryo meminta bantuan kepada Bapak  Muridan untuk mendampingi rombongan dan Pak Dirman yang melanjutkan gerilyanya. </span></p>
            <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-indent:36.0pt;line-height:150%;"><span style="font-size:12.0pt; ">Jendral Sudirman bersinggah di beberapa tempat di  Trenggalek, di Desa Bodag Kecamatan Panggul, Jendral Sudirman bersinggah mulai  31 Januari-03 Februari 1949. Dalam beristirahat di tempat tersebut terdapat  beberapa barang-barang yang pernah dipakai oleh Jendral Sudirman tersebut dan  masih tersimpan sampai sekarang. Barang-barang yang digunakan merupakan  barang-barang yang sederhana dan barang keseharian. Bapak Sukemi selaku cucu  dari Bapak Ngabdi, menunjukkan benda-benda yang pernah dipakai oleh Pak Dirman  waktu bersinggah di tempat ini. Benda-benda tersebut antara lain:</span></p>
            <ol>
            <li><span style="font-size:12.0pt; color:black; ">Sajadah. Sajadah  merupakan alas yang digunakan untuk sholat. Seperti yang telah dijelaskan bahwa  Pak Dirman merupakan tokoh yang religius dan tak pernah meninggalkan sholat.  Sajadah ini sampai sekarang masih disimpan dan dapat dilihat, namun ada bagian  yang sudah rusak. </span></li>
              <li><span style="font-size:12.0pt; color:black; ">Ruang Kamar (Keranjang,  Almari dan Cermin). Di ruang inilah merupakan tempat yang digunakan Pak Dirman  untuk beristirahat selama tiga hari. Di sini terdapat Keranjang Tidur yang  digunakan Pak Dirman untuk beristirahat, ada almari yang digunakan untuk menyimpan  baju dan barang-barang yang dibawa oleh Pak Dirman, dan di sini juga terdapat  cermin yang digunakan oleh Pak Dirman saat berada di sini. Benda-Benda tersebut  masih disimpan sampai saat ini dan dirawat oleh keluarga Bapak Ngabdi termasuk  Bapak Sukemi dan istrinya. </span></li>
              <li><span style="font-size:12.0pt; color:black; ">Peralatan Maka</span><span style="font-size:12.0pt; ">n. <span style="color:black; ">Barang  yang selanjutnya adalah peralatan makan. Disini peralatan makan merupakan  barang yang disiapkan oleh keluarga Bapak Ngabdi waktu Pak Dirman beristirahat  di rumah ini selama 3 hari. Peralatan makan terdiri dari sendok, garpu, mangkok  dan </span>tempat<span style="color:black; "> sup.</span></span></li>
              <li><em><span style="font-size:12.0pt; color:black; "> &ldquo;Paidon&rdquo;. </span></em><span style="font-size:12.0pt; color:black; ">Barang yang </span><span style="font-size:12.0pt; ">keempat<span style="color:black; "> adalah dinamakan <em>&ldquo;paidon&rdquo;</em>. Menurut Bapak Sukemi bahwa  barang ini merupakan barang yang digunakan Pak Dirman untuk membuang ludah dan <em>&ldquo;riyak&rdquo;.</em> Menurut Susilo (2018:65) ketika  situasi nasional yang memanas sekitar bulan November 1948, saat itu juga  Jenderal Sudirman dalam keadaan sakit paru-paru dan menjalani perawatan di  rumahnya. Sehingga <em>paidon</em> ini </span>mengkonfirmasi<span style="color:black; "> cerita tutur dan narasi sejarah nasional tentang sakit  paru-paru yang diderita oleh Jenderal Sudirman. </span></span></li>
              <li><em><span style="font-size:12.0pt; color:black; "> &ldquo;Tandhu&rdquo;.  &ldquo;Tandhu&rdquo;</span></em><span style="font-size:12.0pt; color:black; "> merupakan barang yang tidak kalah penting dalam perang gerilya,  bahwa barang ini merupakan alat yang digunakan untuk membawa Pak Dirman selama  perang gerilya. <em>&ldquo;Tandhu&rdquo;</em> ini dibawa  oleh 4 orang, namun barang tersebut sudah tidak ada di tempat peristirahatan  Desa Bodag, melainkan sudah dibawa oleh pemerintahan Trenggalek. </span></li>
            </ol>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-9.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img class="img-fluid" width="605" height="856" src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-9.jpg"></a></span><span style="font-size:12.0pt; color:black; "> </span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;line-height:normal;border:none;"><strong><span style="font-size:10.0pt; color:black; ">Gambar 9.</span></strong><span style="font-size:10.0pt; color:black; "> Infografis Rumah Singgah Jenderal Sudirman di  Desa Bodag</span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;line-height:normal;border:none;"><span style="font-size:10.0pt; color:black; ">(Sumber:  Dokumentasi Peneliti, 2021)</span></p>
            <p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:7.1pt;text-align:justify;text-indent:35.45pt;line-height:150%;border:none;"><span style="font-size:12.0pt; color:black; ">Berdasarkan transkrip Wawancara Sejarah Lisan (Badan Arsip  Provinsi Jawa Timur, 2003), Pak Muridan menjelaskan bahwa beliau ditugaskan  oleh Pak Partodiwiryo untuk menjadi pengawal atau penunjuk jalan para rombongan  menuju Nglorok, Pacitan. Beliau didatangi langsung oleh </span><span style="font-size:12.0pt; ">sekretaris<span style="color:black; "> Desa Bodag untuk mengantarkan rombongan dari Desa Bodag menuju Nglorok,  Pacitan. Dalam transkrip tersebut dijelaskan bahwa Pak Muridan berangkat lebih  dahulu untuk memastikan jalan baik-baik dan tidak ada pasukan Belanda yang tiba-tiba  berpatroli daerah tersebut, karena memang saat itu kondisi darurat dan Belanda  memang mengincar rombongan gerilya Pak Dirman. Para rombongan berada di  belakang Pak Muridan yang terlebih dahulu menuju Nglorok. Sampai disini  rombongan melanjutkan perjalanan ke Desa Nogosari, Pacitan. Pak Muridan  menjelaskan bahwa di tempat tersebut sudah banyak para pengawal,  menteri-menteri, dokter dan menteri agama saat itu yaitu Pak Haji Masjkur yang  sudah sampai di Desa Nogosari terlebih dahulu (Badan Arsip Provinsi Jawa Timur,  2003).</span></span></p>
            <p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:7.1pt;text-align:justify;text-indent:35.45pt;line-height:150%;border:none;"><a name="_heading=h.gjdgxs"></a><span style="font-size:12.0pt; color:black; ">Di wilayah ini para rombongan mendapatkan  pertolongan dari Pak Lurah dan rakyat Nogosari. Lurah Nogosari tersebut yaitu  paman Iskandar Gondowardoyo yang merupakan Bupati Nganjuk, beliau bernama  Patmowidjojo (Dinas Pembinaan Mental Angkatan Darat, 2008:120). Setelah  melakukan istirahat di tempat ini lalu perjalanan gerilya dilakukan menuju Desa  Gebyur dan dilanjut menuju wilayah Desa Wonokarto, Kecamatan </span><span style="font-size:12.0pt; ">Ngadirojo<span style="color:black; "> Pacitan pada tanggal 18 Februari 1949. Di wilayah ini rombongan gerilya menetap  paling lama dari sekian gerilya yang dilakukan di wilayah lain. Para rombongan  kurang lebih menetap di wilayah ini kurang lebih selama satu bulan. </span></span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;line-height:normal;border:none;"><span style="font-size:12.0pt; "><a href="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-10.jpg" data-toggle="lightbox" data-gallery="materi_1" class="col-4"><img src="<?=base_url()?>/assets/dist/img/foto-materi/materi-2-10.jpg" class="img-fluid" width="675" height="957" align="middle"></a></span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;text-align:center;line-height:normal;border:none;"><strong><span style="font-size:10.0pt; color:black; ">Gambar 10.</span></strong><span style="font-size:10.0pt; color:black; "> Infografis Rute Gerilya di Trenggalek</span></p>
            <p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:21.3pt;text-align:center;line-height:normal;border:none;"><span style="font-size:10.0pt; color:black; ">(Sumber: Dokumentasi  Peneliti, 2021)</span></p>


          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->        
      </div>      
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
